### ISSUE TITLE
Try to contenirized the app

### ISSUE THREAD

**Issue by abdulrahimsulthan** [ostrich-white/asset-management-api#2]
Add a docker file to make a container of an app.

**Comment by ostrich-white** [comment]
Try to add a docker file after merging the current setup-project branch.

**Comment by abdulrahimsulthan** [comment]
@ostrich-white This should be closed the code was merged. [dockerize-app](https://github.com/ostrich-white/asset-management-api/pull/3)

**Comment by ostrich-white** [comment]
PR aproved, feature implemented so this issue is closed.
